// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mixology.Persistence;

#nullable disable

namespace Mixology.Persistence.Migrations
{
    [DbContext(typeof(MixologyDbContext))]
    [Migration("20260809200033_InitialStore")]
    partial class InitialStore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Mixology.Persistence.Model.StoreMetadataRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("store_metadata", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
