<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <MixologyUsesXunitV3>true</MixologyUsesXunitV3>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <ProjectReference Include="../../src/Mixology.Toolkits.Desktop/Mixology.Toolkits.Desktop.csproj" />
  </ItemGroup>
</Project>
