// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mixology.Persistence;

#nullable disable

namespace Mixology.Migrations.Migrations
{
    [DbContext(typeof(MixologyDbContext))]
    [Migration("20260811025803_AddOptimisticRevisions")]
    partial class AddOptimisticRevisions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditEntryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<int?>("ErrorKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_kind");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_id");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Success");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditTouchRow", b =>
                {
                    b.Property<string>("AuditEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("audit_entry_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.HasKey("AuditEntryId", "Position");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_touches", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeIngredientRow", b =>
                {
                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("drink_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL")
                        .HasColumnName("amount");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.Property<bool>("Optional")
                        .HasColumnType("INTEGER")
                        .HasColumnName("optional");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("DrinkId", "Position");

                    b.HasIndex("IngredientId");

                    b.ToTable("drink_recipe_ingredients", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeStepRow", b =>
                {
                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("drink_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("DrinkId", "Position");

                    b.ToTable("drink_recipe_steps", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeSubstituteRow", b =>
                {
                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("drink_id");

                    b.Property<int>("IngredientPosition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ingredient_position");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("SubstituteId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("substitute_id");

                    b.HasKey("DrinkId", "IngredientPosition", "Position");

                    b.HasIndex("SubstituteId");

                    b.ToTable("drink_recipe_substitutes", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Garnish")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("garnish");

                    b.Property<string>("Glass")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("glass");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Glass");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("drinks", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Ingredients.Persistence.IngredientRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Inventory.Persistence.InventoryReservationRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("OrderId");

                    b.ToTable("inventory_reservations", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Inventory.Persistence.InventoryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_updated_utc");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitCostAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost_amount");

                    b.Property<string>("UnitCostCurrency")
                        .HasColumnType("TEXT")
                        .HasColumnName("unit_cost_currency");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId")
                        .IsUnique();

                    b.HasIndex("LastUpdatedUtc");

                    b.ToTable("inventory_stock", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Menus.Persistence.MenuItemRow", b =>
                {
                    b.Property<string>("MenuId")
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_id");

                    b.Property<string>("DrinkId")
                        .HasColumnType("TEXT")
                        .HasColumnName("drink_id");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("availability");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("Featured")
                        .HasColumnType("INTEGER")
                        .HasColumnName("featured");

                    b.Property<decimal?>("PriceAmount")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_amount");

                    b.Property<string>("PriceCurrency")
                        .HasColumnType("TEXT")
                        .HasColumnName("price_currency");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("MenuId", "DrinkId");

                    b.HasIndex("DrinkId");

                    b.HasIndex("MenuId", "SortOrder")
                        .IsUnique();

                    b.ToTable("menu_items", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Menus.Persistence.MenuRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at_utc");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderBlockedIngredientRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<string>("IngredientId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.HasKey("OrderId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("order_blocked_ingredients", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderIngredientUsageRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("IngredientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Quantity")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("unit");

                    b.HasKey("OrderId", "Position");

                    b.HasIndex("IngredientId");

                    b.ToTable("order_ingredient_usage", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderItemRow", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("TEXT")
                        .HasColumnName("order_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("DrinkId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("drink_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.HasKey("OrderId", "Position");

                    b.HasIndex("DrinkId");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("MenuId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("menu_id");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("MenuId");

                    b.HasIndex("Status");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Tagging.Persistence.TagAssociationRow", b =>
                {
                    b.Property<string>("EntityType")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type")
                        .UseCollation("BINARY");

                    b.Property<string>("EntityId")
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id")
                        .UseCollation("BINARY");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key")
                        .UseCollation("BINARY");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1L)
                        .HasColumnName("revision");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value")
                        .UseCollation("BINARY");

                    b.HasKey("EntityType", "EntityId", "Key");

                    b.HasIndex("EntityType", "EntityId");

                    b.HasIndex("Key", "Value");

                    b.ToTable("entity_tags", (string)null);
                });

            modelBuilder.Entity("Mixology.Persistence.Model.StoreMetadataRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("store_metadata", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditTouchRow", b =>
                {
                    b.HasOne("Mixology.Modules.Audit.Persistence.AuditEntryRow", null)
                        .WithMany("Touches")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeIngredientRow", b =>
                {
                    b.HasOne("Mixology.Modules.Drinks.Persistence.DrinkRow", null)
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeStepRow", b =>
                {
                    b.HasOne("Mixology.Modules.Drinks.Persistence.DrinkRow", null)
                        .WithMany("RecipeSteps")
                        .HasForeignKey("DrinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeSubstituteRow", b =>
                {
                    b.HasOne("Mixology.Modules.Drinks.Persistence.DrinkRecipeIngredientRow", null)
                        .WithMany("Substitutes")
                        .HasForeignKey("DrinkId", "IngredientPosition")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Inventory.Persistence.InventoryReservationRow", b =>
                {
                    b.HasOne("Mixology.Modules.Inventory.Persistence.InventoryRow", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .HasPrincipalKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Menus.Persistence.MenuItemRow", b =>
                {
                    b.HasOne("Mixology.Modules.Menus.Persistence.MenuRow", null)
                        .WithMany("Items")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderBlockedIngredientRow", b =>
                {
                    b.HasOne("Mixology.Modules.Orders.Persistence.OrderRow", null)
                        .WithMany("BlockedIngredients")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderIngredientUsageRow", b =>
                {
                    b.HasOne("Mixology.Modules.Orders.Persistence.OrderRow", null)
                        .WithMany("IngredientUsage")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderItemRow", b =>
                {
                    b.HasOne("Mixology.Modules.Orders.Persistence.OrderRow", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditEntryRow", b =>
                {
                    b.Navigation("Touches");
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRecipeIngredientRow", b =>
                {
                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("Mixology.Modules.Drinks.Persistence.DrinkRow", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("RecipeSteps");
                });

            modelBuilder.Entity("Mixology.Modules.Menus.Persistence.MenuRow", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Mixology.Modules.Orders.Persistence.OrderRow", b =>
                {
                    b.Navigation("BlockedIngredients");

                    b.Navigation("IngredientUsage");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
