// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mixology.Persistence;

#nullable disable

namespace Mixology.Migrations.Migrations
{
    [DbContext(typeof(MixologyDbContext))]
    partial class MixologyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditEntryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT")
                        .HasColumnName("error");

                    b.Property<int?>("ErrorKind")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_kind");

                    b.Property<string>("PrincipalId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_id");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at_utc");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("StartedAtUtc");

                    b.HasIndex("Success");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("audit_entries", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditTouchRow", b =>
                {
                    b.Property<string>("AuditEntryId")
                        .HasColumnType("TEXT")
                        .HasColumnName("audit_entry_id");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER")
                        .HasColumnName("position");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.HasKey("AuditEntryId", "Position");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_touches", (string)null);
                });

            modelBuilder.Entity("Mixology.Persistence.Model.StoreMetadataRow", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("store_metadata", (string)null);
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditTouchRow", b =>
                {
                    b.HasOne("Mixology.Modules.Audit.Persistence.AuditEntryRow", null)
                        .WithMany("Touches")
                        .HasForeignKey("AuditEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mixology.Modules.Audit.Persistence.AuditEntryRow", b =>
                {
                    b.Navigation("Touches");
                });
#pragma warning restore 612, 618
        }
    }
}
